[build]
  base = "web/"
  command = "npm run build"
  publish = "public"

[context.staging.environment]
  NODE_ENV = "development"

[context.preview.environment]
  NODE_ENV = "development"

[[redirects]]
  from = "/seu"
  to = "https://searchengineunity.com/"
  status = 200
  force = true 
