[build]
  base = "web/"
  command = "npm run build"
  publish = "public"

[context.staging.environment]
  NODE_ENV = "development"

[context.preview.environment]
  NODE_ENV = "development"

[[redirects]]
  from = "/*"
  to = "https://reverse-proxy-test.netlify.app/:splat"
  status = 200
  force = true  